parameters:
  secret: ThisTokenIsNotSoSecretChangeIt
  project_prefix: 5TALOS
  project_name: Project Name X
  
  uploads_directory: '%kernel.root_dir%/../web/uploads/'
twig:
    globals:
        project_name: %project_name%
    form_themes: 
        - '@CoreSystemBundle\Resources\views\Default\forms.html.twig'