imports:
    - { resource: 'database.yml' }
    - { resource: 'mail.yml' }
    - { resource: 'locale.yml' }
    - { resource: 'bundles.yml' }

parameters:
  secret: ThisTokenIsNotSoSecretChangeIt
  project_prefix: 5TALOS
  project_name: Project Name X
  
  uploads_directory: '%kernel.root_dir%/../web/uploads/'
twig:
    globals:
        project_name: %project_name%
    form_themes: 
        - '@AdminBundle\Resources\views\Default\forms.html.twig'